### ISSUE TITLE
Hole ring is not closed

### ISSUE THREAD

**Issue by matthew-kersting** [ctlee/gamer#36]
When I decimate selected dense areas of the mesh I am getting the error: "ERROR(coarse): Hole ring is not closed. Please contact the developers with this error." CellBlender says this is a watertight/manifold mesh and I have tried manually deleting non-manifold edges then filling holes.

**Comment by ctlee** [comment]
Can you please provide some additional details and also possibly share the mesh you are operating on. In particular what settings for coarse dense are you using and the blendgamer version.

**Comment by matthew-kersting** [comment]
Of course. Here is the mesh. 

[VCN_c05_SinputTerminal03_Deci.obj.zip](https://github.com/ctlee/gamer/files/3315699/VCN_c05_SinputTerminal03_Deci.obj.zip)

I am in Blender 2.79 using the gamer blender add-on off this repo (downloaded a couple days ago). The mesh is quite large, so when I load in the mesh I scale it down and then use Blender's decimation modifier to make it more manageable. Then I delete non-manifold vertices and close holes (This is the mesh version that is attached here). Finally I analyze the mesh in CellBlender and use coarse dense at a rate of 0.76 and 5 iterations.

**Comment by ctlee** [comment]
Thanks for sending the info and for trying out GAMer! I took a look and this is a known issue with the `coarse` operations. If you take your object and split it by connected surfaces (defined by edge/face connectivity, not spatial). You'll find that there are really 21 surface meshes in this object.

![image](https://user-images.githubusercontent.com/6172509/59955200-c3c69c80-943d-11e9-8a45-bec814260836.png)

**What happens when coarse is called?** 
The `coarse` operation marks vertices for deletion by the user defined threshold. Then the resulting hole is retriangulated. 

**Why are you getting this error?**
For many of the smaller surface blobs, the iterative deletion of vertices followed by retriangulation can lead to very sparse meshes. In the worst, case they can become a single tetrahedron 4 vertices, 6 edges, and 6 faces. In this case, the removal of a vertex followed by retriangulation results in the "reinsertion" of the remaining face (which CASC allows without warning currently). At the next step, you're decimating an object with only one face and the behavior becomes undefined and caught by this error message.

**Possible solution**
What I would recommend is for you to split the mesh into multiple objects by connectivity. You can then operate on them as you would like. When you have a mesh you're happy with, if this is desired, you can merge the objects back into one.

**Steps for GAMer Development**
Happy to get your feedback on any other suggested steps which would help you and other users.

- [ ] Document this eccentricity and update the error message to link to the discussion.
- [ ] Add checks for decimations which can lead to undefined behaviors. These checks would lead to a penalty in runtime speed and are thus not preferred. But we could work towards something like 'strict' GAMer operation where these kinds of issues are checked.

**Comment by matthew-kersting** [comment]
Thank you for the help and for building GAMer. I appreciate you taking some time to help me on this issue. Splitting the mesh by connected surfaces resolved the issue (most of the disconnected pieces were artifacts that needed to be thrown away).
