### ISSUE TITLE
Can't Identify atoms in pdb file

### ISSUE THREAD

**Issue by chang-github-00** [ctlee/gamer#51]
When loading a pdb file, can't identify many atoms even though they are all valid. 
```Could not find atomtype of ' H  ' in residue 'CYS'. Using default radius.
Could not find atomtype of ' HA ' in residue 'CYS'. Using default radius.
Could not find atomtype of ' HB1' in residue 'CYS'. Using default radius.
Could not find atomtype of ' HB2' in residue 'CYS'. Using default radius.
Could not find atomtype of ' HG ' in residue 'CYS'. Using default radius.
Could not find atomtype of ' HA ' in residue 'PRO'. Using default radius.
Could not find atomtype of ' HB1' in residue 'PRO'. Using default radius.
Could not find atomtype of ' HB2' in residue 'PRO'. Using default radius.
Could not find atomtype of ' HG1' in residue 'PRO'. Using default radius.
Could not find atomtype of ' HG2' in residue 'PRO'. Using default radius.
Could not find atomtype of ' HD1' in residue 'PRO'. Using default radius.
Could not find atomtype of ' HD2' in residue 'PRO'. Using default radius.
Could not find atomtype of ' OXT' in residue 'PRO'. Using default radius.```

**Comment by ctlee** [comment]
The PDB reader uses a dictionary  which converts maps a residue name and atomtype to a radius. Here we didn't include values for many hydrogens and in this case the terminal oxygen. 

You can see the list of atomtypes defined here: https://github.com/ctlee/gamer/blob/master/include/gamer/PDBReader.h#L72-L242

Since we cannot be comprehensive with respect to the various force fields the default list is very sparse. I recommend that you use a tool like PDB2PQR to generate a PQR file which includes the radii of each atom in the file. You'll have the benefit of getting atomic radii from a specific force field and it will avoid these unknown atomtype errors.
