### ISSUE TITLE
Blender 3.2.2

### ISSUE THREAD

**Issue by torquil** [ctlee/gamer#56]
Hi!

Is it expected that the addon should work in Blender 3.2.2? I used CMake to install libgamer, and then installed pygamer. "import pygamer" works fine within python3. However, when install and try to activate the blendgamer addon in Blender 3.2.2 I get the following error:

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/torquil/.config/blender/3.2/scripts/addons/blendgamer/__init__.py", line 47, in <module>
    from . import (
  File "/home/torquil/.config/blender/3.2/scripts/addons/blendgamer/blendgamer.py", line 37, in <module>
    from blendgamer.surfacemesh_ops import SurfaceMeshImprovementProperties
  File "/home/torquil/.config/blender/3.2/scripts/addons/blendgamer/surfacemesh_ops.py", line 36, in <module>
    import blendgamer.pygamer as g
ModuleNotFoundError: No module named 'blendgamer.pygamer'

Best regards,
Torquil Sørensen

**Comment by torquil** [comment]
I now suspect that this happens because the blendgamer addon that I downloaded is meant for Python3.9, while I have Python3.10. Will you release a Python3.10 version some time soon?

Best regards,
Torquil Sørensen

**Comment by ctlee** [comment]
I'd expect that the add-on should work with Blender 3.2.2 although I haven't tested it myself.  I haven't had a chance to review the Blender python API changes since the previous LTS version (2.93) and likely won't have time to do a detailed review before the end of this year.

If you're willing to help test the add-on, there's two options:

1. You can build for python 3.10 yourself. Building BlendGAMer is a little tricky, as you suggested, due to the requirement to  match the Blender python version. Some instructions for building can be found here: [Building BlendGAMer](https://gamer.readthedocs.io/en/latest/install.html#blendgamer-the-harder-way)

2. We can add python 3.10 to CI and I can share a build artifact for you to test. If you find any errors, we can discuss here and implement fixes.

WDYT?
