### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BJWiley233** [ctlee/gamer#63]
Hi,

I was potentially trying to use pygamer so I could create a geometric graph somehow with torch_geometric.  I ran into one problem in that I have a GLUT3/B-glucose (protein and ligand) however I get more than two meshes.  I get 1 big mesh for most of the protein, then I have 9 other smaller meshes in which the largest of of those is probably the B-glucose but the rest seem to be little surfaces on the interior (solvent inaccessible region) of the protein.  Could I send the PDB file to see why this might be? 

On the topic of assigning vertices and edges onto a geometric graph, is it possible to map the vertices and/or edges to which atoms they are associated with/to or are most associated to which atoms of the pdb?

Thanks
Brian

**Comment by ctlee** [comment]
It's possible that due to atom spacing there's some other small packing defects. The radii use for applying Gaussian's also isn't very carefully tuned. If your goal is to have just the surface mesh of the protein, you could just remove the smaller meshes. If you want to omit them completely, you can change things like the grid resolution or change some of the input parameters. 

It's possible to map vertices or edges to atoms. But there's no function for this at this point. You can do traversals of the mesh in using pyGAMer or you can load the mesh into another mesh library.
