### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MartinAchondo** [ctlee/gamer#64]
Hi there!

I've been working with the PyGamer code and I was wondering if there's a way to redirect the output prints generated by the code to a logfile (the -pygamer.makeTetMesh(meshes, "tetgen_string")- method). Currently, I'm finding it a bit difficult to track the execution flow and debug any issues without having a centralized log file to refer to. This outputs must contain also the ones generated by the string command passed to TetGen.

Could someone please advise if there's a built-in feature for this in either PyGamer or TetGen? Or perhaps recommend a  technique to achieve this? 

Any help or pointers would be greatly appreciated! 
Thanks in advance!

**Comment by ctlee** [comment]
You could capture the output through standard shell redirections (https://www.gnu.org/software/bash/manual/html_node/Redirections.html). We're just calling tetgen using their API so all logging would have to happen in tetgen code. FWIW Tetgen with verbose flags do output some details. You could also try a debugger depending on what the actual issue is. 

If you give more specifics about the problem you're having, I may have better suggestions. Please feel free to reopen with details.
